name: upload_beta

on:
  # Trigger a TestFlight build on push,
  # but only for the master branch
  push:
    branches:
      - testflight

env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:
  testflight_upload:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: TestFlight Upload
      run: |
        gem install bundler:1.16.6
        bundle install
        bundle exec fastlane beta
      env:
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.TOKEN_FOR_PROFILES }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
        FASTLANE_APPLE_ID: ${{ secrets.FASTLANE_APPLE_ID }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}